<<<<<<< HEAD
backend:
  name: git-gateway
  branch: main   # use "master" se seu repositório estiver assim

media_folder: "static/img"
public_folder: "/img"

collections:
  - name: "posts"
    label: "Posts"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Título", widget: "string" }
      - { name: "date", label: "Data", widget: "datetime" }
      - { name: "body", label: "Conteúdo", widget: "markdown" }
=======
backend:
  name: git-gateway
  branch: main   # use "master" se seu repositório estiver assim

media_folder: "static/img"
public_folder: "/img"

collections:
  - name: "posts"
    label: "Posts"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Título", widget: "string" }
      - { name: "date", label: "Data", widget: "datetime" }
      - { name: "body", label: "Conteúdo", widget: "markdown" }
>>>>>>> 9ca27be0bb48fa7c46bf7fc79dd351dbcf8c2aa1
