backend:
  name: github
  repo: namir15/site
  branch: main
  auth_scope: repo

media_folder: "static/img"
public_folder: "/img"

collections:
  - name: "posts"
    label: "Posts"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Título", widget: "string" }
      - { name: "date", label: "Data", widget: "datetime" }
      - { name: "body", label: "Conteúdo", widget: "markdown" }
